NAME        = so_long
CC			= gcc
# CFLAGS	= -Wall -Wextra -Werror
CFLAGS		= -Werror
MLX_FLAGS	= -Imlx_linux -lXext -lX11 -lm -lz
RM             = /bin/rm -f

INCS_DIR    = ./includes
LIBFT_DIR    = ./libft
LIBFT        = $(LIBFT_DIR)/libft.a

BUILD_DIR    = build
SRC_DIR        = ./srcs
SRCS        = main.c

OBJS = $(SRCS:%.c=$(BUILD_DIR)/%.o)

all: $(NAME)

$(OBJS): $(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(@D)
	@echo "Compiling $<"
	$(CC) $(CFLAGS) -I/usr/local/include -Imlx_linux -O3 -c $< -o $@

$(NAME): $(OBJS)
	$(CC) $(OBJS) -Lmlx_linux -lmlx_Linux -L/usr/local/lib $(MLX_FLAGS) -o $(NAME)
	@echo "Done!"


bonus: all

clean:
	$(RM) $(OBJS)

fclean: clean
	# $(RM) $(NAME)

re: fclean all
	
.PHONY: all clean fclean re