#ifndef FILE_H
#define FILE_H
// # define MAP_FILE				"maps/simple.ber"
// # define MAP_FILE				"maps/errors/test"
// # define MAP_FILE				"maps/errors/empty.ber"
// # define MAP_FILE				"maps/errors/not_rect.ber"
// # define MAP_FILE				"maps/errors/no_file.ber"
// # define MAP_FILE				"maps/errors/no_exit.ber"
// # define MAP_FILE				"maps/errors/no_item.ber"
// # define MAP_FILE				"maps/errors/no_sprite.ber"
// # define MAP_FILE				"maps/errors/no_wall.ber"
// # define MAP_FILE				"maps/simple.ber"
# define MAP_FILE					"maps/simple_mon.ber"
// # define MAP_FILE				"maps/large.ber"

# define OBJECT_WALL_PATH			"objects/wall.xpm"
# define OBJECT_ITEM_PATH			"objects/elixir_small.xpm"
# define OBJECT_GRASS_PATH			"objects/grass.xpm"
# define OBJECT_EXIT_PATH			"objects/door.xpm"
# define SPRITE_STAND_LEFT_PATH		"players/cele_stand_left.xpm"
# define SPRITE_STAND_RIGHT_PATH	"players/cele_stand_right.xpm"
# define SPRITE_STAND_UP_PATH		"players/cele_stand_up.xpm"
# define SPRITE_STAND_DOWN_PATH		"players/cele_stand_down.xpm"
# define SPRITE_KNEEL_PATH			"players/cele_sit.xpm"
# define SPRITE_HURT_PATH			"players/cele_hurt.xpm"
# define SPRITE_FALLEN_PATH			"players/cele_fallen.xpm"
# define SPRITE_WALK_LEFT1_PATH		"players/cele_walk_left_1.xpm"
# define SPRITE_WALK_LEFT2_PATH		"players/cele_walk_left_2.xpm"
# define SPRITE_WALK_RIGHT1_PATH	"players/cele_walk_right_1.xpm"
# define SPRITE_WALK_RIGHT2_PATH	"players/cele_walk_right_2.xpm"
# define SPRITE_WALK_UP1_PATH		"players/cele_walk_up_1.xpm"
# define SPRITE_WALK_UP2_PATH		"players/cele_walk_up_2.xpm"
# define SPRITE_WALK_DOWN1_PATH		"players/cele_walk_down_1.xpm"
# define SPRITE_WALK_DOWN2_PATH		"players/cele_walk_down_2.xpm"
# define BOSS_PATH					"bosses/altos.xpm"
# define ENEMY_STAND_LEFT_PATH		"enemies/ghost_stand_left.xpm"
# define ENEMY_STAND_RIGHT_PATH		"enemies/ghost_stand_right.xpm"
# define ENEMY_STAND_BACK_PATH		"enemies/ghost_stand_back.xpm"
# define ENEMY_STAND_FRONT_PATH		"enemies/ghost_stand_front.xpm"
# define ENEMY_WALK_LEFT1_PATH		"enemies/ghost_walk_left_1.xpm"
# define ENEMY_WALK_LEFT2_PATH		"enemies/ghost_walk_left_2.xpm"
# define ENEMY_WALK_RIGHT1_PATH		"enemies/ghost_walk_right_1.xpm"
# define ENEMY_WALK_RIGHT2_PATH		"enemies/ghost_walk_right_2.xpm"
# define ENEMY_WALK_UP1_PATH		"enemies/ghost_walk_back_1.xpm"
# define ENEMY_WALK_UP2_PATH		"enemies/ghost_walk_back_2.xpm"
# define ENEMY_WALK_DOWN1_PATH		"enemies/ghost_walk_front_1.xpm"
# define ENEMY_WALK_DOWN2_PATH		"enemies/ghost_walk_front_2.xpm"
#endif